salty/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import surfers.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(surfers.urls)),
]

surfers/urls.py
from django.conf.urls import url
import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^surfers/$', views.surfers),
    url(r'^surfers/(?P<surfer_pk>\d+)/$', views.surfer),
    url(r'^shapers/$', views.shapers),
    url(r'^shapers/(?P<shaper_pk>\d+)/$', views.shaper),
    url(r'^surfboards/$', views.surfboards),
    url(r'^surfboards/(?P<surfboard_pk>\d+)/$', views.surfboard),
    url(r'^surfboard_models/$', views.surfboard_models),
    url(r'^surfboard_models/(?P<surfboard_model_pk>\d+)/$', views.surfboard_model),
]

surfers/models.py
from django.db import models


class Surfer(models.Model):
    name = models.CharField(max_length=200)
    skill = models.PositiveIntegerField()

    bio = models.TextField(blank=True)
    image_url = models.URLField(blank=True)

class Shaper(models.Model):
    name = models.CharField(max_length=200)
    shaping_since = models.DateField()
    label = models.CharField(max_length=200)
    bio = models.TextField(blank=True)

    website_url = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s (since %s)' % (self.name, self.shaping_since.year)

class SurfboardModel(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)

class Surfboard(models.Model):
    name = models.CharField(max_length=200)
    length = models.FloatField()
    width = models.FloatField()

    description = models.TextField(blank=True)
    image_url = models.URLField(blank=True)

    created_at = models.DateField(auto_now_add=True)

    shapers = models.ManyToManyField(Shaper) #changed from shaper, ForeignKey
    surfer = models.ForeignKey(Surfer)
    surfboard_model = models.ForeignKey(SurfboardModel, null=True, blank=True)

    @property
    def display_length(self):
        return '''%s' - %s"''' % (int(self.length / 12), self.length % 12)

    @property
    def display_dimensions(self):
        return u'%s x %s"' % (
            self.display_length,
            self.width,
        )

    def __unicode__(self):
        return u'%s by %s (%s) model: %s' % (
            self.name,
            self.shapers.all(), #Changed from .name
            self.display_dimensions,
            self.surfboard_model
        )

surfers/views.py
from django.shortcuts import (
    render, get_object_or_404,
)
from django.db.models import Max

from surfers.models import (
    Surfer, Shaper, Surfboard, SurfboardModel
)

def index(request):
    print 'hello'
    return render(request, 'index.html', {
        'new_surfboards': Surfboard.objects.order_by('-created_at')[:3],
        'updated_shapers': Shaper.objects.annotate(recent=Max('surfboard__created_at')).order_by('-recent')[:2]
    })

def surfers(request):
    surfers = Surfer.objects.all()
    return render(request, 'surfers.html', {
        'surfers': surfers,
    })

def surfer(request, surfer_pk):
    surfer = get_object_or_404(Surfer, pk=surfer_pk)
    return render(request, 'surfer.html', {
        'surfer': surfer,
    })

def shapers(request):
    shapers = Shaper.objects.all()
    return render(request, 'shapers.html', {
        'shapers': shapers,
    })


def shaper(request, shaper_pk):
    shaper = get_object_or_404(Shaper, pk=shaper_pk)
    return render(request, 'shaper.html', {
        'shaper': shaper,
    })

def surfboards(request):
    surfboards = Surfboard.objects.all()
    return render(request, 'surfboards.html', {
        'surfboards': surfboards,
    })


def surfboard(request, surfboard_pk):
    surfboard = get_object_or_404(Surfboard, pk=surfboard_pk)
    return render(request, 'surfboard.html', {
        'surfboard': surfboard,
    })

def surfboard_models(request):
    surfboard_models = SurfboardModel.objects.all()
    print surfboard_models
    return render(request, 'surfboard_models.html', {
        'surfboard_models': surfboard_models
    })

def surfboard_model(request, surfboard_model_pk):
    surfboard_model = get_object_or_404(SurfboardModel, pk=surfboard_model_pk)
    return render(request, 'surfboard_model.html', {
        'surfboard_model': surfboard_model
    })

surfers/templates/index.html
{% extends 'base.template' %}

{% block nav_home_classes %}
  active
{% endblock %}

{% block content %}
  
  <div class="page-header">
    <h1>Hey, this is a silly little website about surfboards.</h1>
  </div>

  <div class="row">

    <div class="col-md-6">
      <h3>New Surfboards</h3>
      {% include 'shared/surfboards.template' with surfboards=new_surfboards %}
    </div>

    <div class="col-md-6">
      <h3>Shaper Updates</h3>
      {% include 'shared/shapers.template' with shapers=updated_shapers %}
    </div>

  </div>

{% endblock %}

{% block quote %}
  Nobody listens to Turtle.
{% endblock %}

surfers/templates/shaper.html
{% extends 'base.template' %}

{% block nav_shapers_classes %}
  active
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-md-4">
    
      <h2>{{ shaper.name }}</h2>
      <h4>{{ shaper.label }}</h4>
    
      <dl>
        <dt>Shaping since</dt>
        <dd>{{ shaper.shaping_since }}</dd>
      </dl>
      
      <p class="bio">
        {{ shaper.bio }}
      </p>
  
    </div>

    <div class="col-md-8">
      <p class="lead">{{ shaper.name }}'s boards:</p>
      {% include 'shared/surfboards.template' with surfboards=shaper.surfboard_set.all %}
    </div>
  </div>

{% endblock %}

surfers/templates/shapers.html
{% extends 'base.template' %}

{% block nav_shapers_classes %}
  active
{% endblock %}

{% block content %}  
  <div class="page-header">
    <h1>Shapers</h1>
  </div>

  {% include 'shared/shapers.template' %}
{% endblock %}

{% block quote %}
  When the waves break here don’t be there, or you gonna get drilled.
{% endblock %}

surfers/templates/surfboard.html
{% extends "base.template" %}

{% block content %}
  <h2>
    {{ surfboard.name }}:
    <span class="dimensions">{{ surfboard.display_dimensions }}</span>
  </h2>
  <h2>Model</h2>
  {% include 'shared/surfboard_model.template' with surfboard_model=surfboard.surfboard_model %}

  <h2>Shaper</h2>
  {% include 'shared/shapers.template' with shapers=surfboard.shapers.all %}

  <h2>Current Owner</h2>
  {% include 'shared/surfer.template' with surfer=surfboard.surfer %}
{% endblock %}

surfers/templates/surfboard_model.html
{% extends "base.template" %}

{% block content %}
  <div class="row">
    <div class="col-md-4">
    
      <h2>{{ surfboard_model.name }}</h2>    
      <dl>
        <dt>Description</dt>
        <dd>{{ surfboard_model.description }}</dd>
      </dl>
  
    </div>

    <div class="col-md-8">
      <p class="lead">{{ surfboard_model.name }}'s boards:</p>
      {% include 'shared/surfboards.template' with surfboards=surfboard_model.surfboard_set.all %}
    </div>
  </div>
{% endblock %}

surfers/templates/surfboard_models.html
{% extends 'base.template' %}

{% block nav_surfboard_models_classes %}
  active
{% endblock %}

{% block content %}  
  <div class="page-header">
    <h1>Surfboard Models</h1>
  </div>

  {% include 'shared/surfboard_models.template' %}
{% endblock %}

{% block quote %}
  Just paddling out can be a national disaster.
{% endblock %}

surfers/templates/surfboards.html
{% extends 'base.template' %}

{% block nav_surfboards_classes %}
  active
{% endblock %}

{% block content %}  
  <div class="page-header">
    <h1>Surfboards</h1>
  </div>

  {% include 'shared/surfboards.template' %}
{% endblock %}

{% block quote %}
  Just paddling out can be a national disaster.
{% endblock %}

surfers/templates/surfer.html
{% extends "base.template" %}

{% block nav_surfers_classes %}
  active
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-md-4">
  
      <h2>{{ surfer.name }}</h2>
      {% include 'shared/surfer.template' %}
  
      <p class="bio">
        {{ surfer.bio }}
      </p>
  
    </div>
    <div class="col-md-8">
      
      <h3>{{ surfer.name }}'s boards:</h3>
      
      {% include 'shared/surfboards.template' with surfboards=surfer.surfboard_set.all %}
    </div>
  </div>

{% endblock %}

surfers/templates/surfers.html
{% extends 'base.template' %}

{% block nav_surfers_classes %}
  active
{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>Surfers</h1>
  </div>

  {% include 'shared/surfers.template' %}
{% endblock %}

{% block quote %}
  I thought I told you to go home.
{% endblock %}